/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.demo;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import ru.bsuedu.cad.demo.app.Client;;

public class App {
        private static final Logger LOGGER = LoggerFactory.getLogger(App.class);
    public static void main(String[] args) {
   
        var ctx = new AnnotationConfigApplicationContext(ConfigJpa.class);
        var client = ctx.getBean(Client.class);
        client.run();
    }
}
