/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cap.component;

import java.util.Arrays;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;


public class App {
    public static void main(String[] args) {
        ApplicationContext ctx = new AnnotationConfigApplicationContext(Config.class);
        Arrays.stream(ctx.getBeanDefinitionNames()).forEach(beanName -> System.out.println(beanName));
         Renderer mr = ctx.getBean("renderer", Renderer.class);
         mr.render();
          }
    }
