/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.stereotype.Component;

@Component
public class App {


    public static void main(String[] args) {
        ApplicationContext ctx = new AnnotationConfigApplicationContext(AppConfiguration.class);
        ((App) ctx.getBean("app")).run();
    }

        final Person person;

    @Autowired
    public App(Person orator) {
        this.person = orator;

    }

    public void run() {
        person.say();
        person.scream();
    }
}
