/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cap.hello;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        AppWithoutConfiguration classUnderTest = new AppWithoutConfiguration();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
