/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cap.hello;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.GenericGroovyApplicationContext;

public class AppWithSpringGroovy {
    public static void main(String[] args) {
        ApplicationContext ctx = new GenericGroovyApplicationContext("spring/app-context.groovy");
        MessageRenderer messageRenderer = ctx.getBean("renderer", MessageRenderer.class);
        messageRenderer.render();
     }
}
