/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cap.hello;

import ru.bsuedu.cap.hello.impl.MessageProviderImpl;
import ru.bsuedu.cap.hello.impl.MessageRendererImpl;

public class AppWithoutConfiguration {

    public static void main(String[] args) {
       MessageProvider messageProvider = new MessageProviderImpl();
       MessageRenderer messageRenderer = new MessageRendererImpl();
       messageRenderer.setMessageProvider(messageProvider);
       messageRenderer.render();
    }
}
