/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cap.hello;

import java.util.ServiceLoader;

public class AppWithServiceLoader {
    public static void main(String[] args) {
        ServiceLoader<MessageRenderer> slr = ServiceLoader.load(MessageRenderer.class);
        ServiceLoader<MessageProvider> slp = ServiceLoader.load(MessageProvider.class);

        MessageRenderer messageRenderer = slr.findFirst().orElseThrow(() -> new IllegalArgumentException("Service of type 'MessageRenderer' was not found!"));
        MessageProvider messageProvider = slp.findFirst().orElseThrow(() -> new IllegalArgumentException("Service of type 'MessageProvider' was not found!"));
        messageRenderer.setMessageProvider(messageProvider);
        messageRenderer.render();
     }
}
